### ISSUE TITLE
Export full maze as well

### ISSUE THREAD

**Issue by pmeems** [adashrod/LaserCutMazesAnguglar#2]
It is a really great library/tool.
I would like a slightly different maze. You already have it, but not export it as an SVG.

I would like this image as SVG as well:
![image](https://user-images.githubusercontent.com/12067729/44618796-52e64080-a87d-11e8-96a5-2e8da71b3e48.png)
Then I can use it to cut out a piece of wood. Glue it on a full sheet of wood, add a small marble and glue a transparent acrylic sheet on top. Like a sandwich.

Here's an example:
![image](https://user-images.githubusercontent.com/12067729/44618873-6cd45300-a87e-11e8-9868-dcd0a4b68ae7.png)
The yellow sheet is underneath. The red sheet is cut and glued on top of it.

I hope you understand what I mean, I'm not a native English speaker ;)

**Comment by adashrod** [comment]
Yes, I can add that feature. Just one question about this: do you plan to use the sheet with the existing cutout walls or by itself?

**Comment by pmeems** [comment]
I want to use the sheet without the cutout walls.

**Comment by adashrod** [comment]
Got it. I'll make it happen.

**Comment by adashrod** [comment]
This feature is now available on https://adashrod.github.io/LaserCutMazes/ . Let me know if you have any questions or issues with it. Enjoy!
